### ISSUE TITLE
Problems creating conda environment (old torchvision version)

### ISSUE THREAD

**Issue by abailoni** [kreshuklab/gpu_envs#2]
Hello people ;)

Is the `base-env.yaml` file in the repo still up to date? When I try to create an environment with it, I get a very old version of torchvision (0.2.2). This seems to be a problem related to the other dependencies, because if I install only cuda, pytorch and torchvision I get all the right versions, but if I only try to add vigra as dependency (which I also need) then I get the outdated torchvision version. I also tried to manually specify torchvision=0.8.2, but then I get the CPU version instead of the cuda one. Have you ever noticed this? 

I also tried to remove the requirement for PyTorch 1.7.1 and in that case PyTorch 1.7 is correctly installed (with the proper associated torchvision version), but the only easy build version available is PyTorch 1.7.1.

In general, I am having quite some troubles finding a version of PyTorch/CUDA that works on the nodes with RTX 3090: I tried with PyTorch 1.7, 1.9, and several versions of CUDA, but I always get complains about incompatible CUDA version. And I was hoping that the easybuild version would work. I have a working setup on the nodes with 2080Ti, but for one of the tasks I need to do I would need more than 12G of memory.

Thank you!

**Comment by constantinpape** [comment]
> I also tried to remove the requirement for PyTorch 1.7.1

Yes, easybuild only provides 1.7.1 right now. You could ping Juri if you need a newer version.

In general the environment shold work; I am not using torchvision much so not sure about the versions there.

**Comment by abailoni** [comment]
Thank you Constantin. 

Yeah, unfortunately I need torch vision for an external library. In any case now I found that this is a known bug in [torch vision](https://github.com/pytorch/vision/issues/4076) that was found few months ago but it’s not fixed yet. I tried all versions of PyTorch and 1.7.0 seems to be the only one not affected by it.
